import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Rightside from "@/components/rightside";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "葱苓sama",
  description: "a small blog station generated by create next app.",
  icons: '/ciraos.webp',
};

export default function RootLayout({children,}:Readonly<{children:React.ReactNode;}>){
  return (
    <html lang="zh-CN" className={inter.className}>
      {/* <body className={inter.className}>{children}</body> */}
      <body className="">
        <Navbar />
        {/* <Banner /> */}
        {children}
        <Footer />
        {/* <Rightside /> */}
      </body>
    </html>
  );
}
